### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by alexritt97** [embl-cba/microglia-morphometry#10]
Hello, 
I am unfortunately getting exceptions when trying to run either the segmentation or measure functions. When using either your example input images or my own I receive errors. Is it currently working for others?

**Comment by alexritt97** [comment]
Of course, 
I use this as an input for new microglia segmentation and tracking: 
![image](https://github.com/embl-cba/microglia-morphometry/assets/161772857/bf3f6e05-54c4-4efd-9d08-df0371e541b1)

This is as far as the log gets if that means anything
![image](https://github.com/embl-cba/microglia-morphometry/assets/161772857/3b390ba0-31bf-4a26-a0a3-03198e019aa7)

And then this is the exception:
![image](https://github.com/embl-cba/microglia-morphometry/assets/161772857/fd7620fb-46e1-4679-a29f-29873e9b687f)
pt2 
![image](https://github.com/embl-cba/microglia-morphometry/assets/161772857/a6bb2bd4-49df-400f-a76c-1ed08903e206)

And then when using that same image and the mask I generated for it last week, I get this error for measure
![image](https://github.com/embl-cba/microglia-morphometry/assets/161772857/73f2129d-27a8-4c11-ad18-959eea3943a1)
![image](https://github.com/embl-cba/microglia-morphometry/assets/161772857/4b73c39f-a6d1-4ee2-8889-dcdc47868e79)

(Fiji Is Just) ImageJ 2.14.0/1.54i; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 102MB of 12036MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:128)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.IllegalArgumentException: Multiple 'net.imagej.ops.morphology.thin.ThinGuoHall' ops of priority 0.0:
1. (RandomAccessibleInterval out?) =
	net.imagej.ops.morphology.thin.ThinGuoHall(
		RandomAccessibleInterval out?,
		RandomAccessibleInterval in)
2. (RandomAccessibleInterval out?) =
	net.imagej.ops.morphology.thin.ThinGuoHall(
		RandomAccessibleInterval out?,
		RandomAccessibleInterval in)

Request:
-	net.imagej.ops.morphology.thin.ThinGuoHall(
		IntervalView)

Candidates:
1. 	(RandomAccessibleInterval out?) =
	net.imagej.ops.morphology.thin.ThinGuoHall(
		RandomAccessibleInterval out?,
		RandomAccessibleInterval in)
2. 	(RandomAccessibleInterval out?) =
	net.imagej.ops.morphology.thin.ThinGuoHall(
		RandomAccessibleInterval out?,
		RandomAccessibleInterval in)

	at net.imagej.ops.DefaultOpMatchingService.singleMatch(DefaultOpMatchingService.java:431)
	at net.imagej.ops.DefaultOpMatchingService.findMatch(DefaultOpMatchingService.java:96)
	at net.imagej.ops.DefaultOpMatchingService.findMatch(DefaultOpMatchingService.java:82)
	at net.imagej.ops.OpEnvironment.module(OpEnvironment.java:269)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:157)
	at net.imagej.ops.morphology.MorphologyNamespace.thinGuoHall(MorphologyNamespace.java:62)
	at de.embl.cba.morphometry.Algorithms.createObjectSkeletons(Algorithms.java:849)
	at de.embl.cba.morphometry.skeleton.SkeletonCreator.run(SkeletonCreator.java:84)
	at de.embl.cba.microglia.measure.MicrogliaMorphometry.createSkeletons(MicrogliaMorphometry.java:132)
	at de.embl.cba.microglia.measure.MicrogliaMorphometry.run(MicrogliaMorphometry.java:45)
	at de.embl.cba.microglia.command.MicrogliaMorphometryCommand.run(MicrogliaMorphometryCommand.java:66)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	... 6 more

**Comment by tischi** [comment]
Thanks @alexritt97!

This is new to me and I am not sure what is going on.

I am asking the [experts here](https://imagesc.zulipchat.com/#narrow/stream/327237-SciJava/topic/Multiple.20'net.2Eimagej.2Eops.2Emorphology.2Ethin.2EThinGuoHall'.20ops.2E.2E.2E).

i will get back to you once I could fix it.

**Comment by ctrueden** [comment]
That can happen if there are two `PluginInfo` instances pointing to the same plugin, which can happen if there is duplicate plugin metadata in `META-INF/json/org.scijava.plugin.Plugin`. Let's try to make a minimal example to reproduce. Does the problem happen if you run the following Groovy script in the Script Editor?
```groovy
#@ OpService ops
#@ Img img
mask = ops.threshold().otsu(img)
ops.morphology().thinGuoHall(mask)
```
?

I tried in my local installation on the Blobs sample image, and it works for me. It might depend which update site(s) are enabled.

**Comment by tischi** [comment]
This works for me, too, in a freshly updated Fiji with only the Microglia-Morphometry update site.

@alexritt97 could you please also try?

1. `File > Open Samples > Blobs`
2. `File > New Script`
3. Copy the code above into the script editor window
4. Script Editor: `Language > Groovy`
5. Script Editor: `Run`

<img width="747" alt="image" src="https://github.com/embl-cba/microglia-morphometry/assets/2157566/8a41eb32-5fad-44a6-96fa-eb51e73e876d">

**Comment by alexritt97** [comment]
Thank you so much for this, both of those groovy scripts worked for me so I
went and did some cleaning up of my plugins and updated things again and it
is no longer happening! Not sure what exactly caused it along the line but
I really appreciate your help!
