### ISSUE TITLE
Opening output in MoBIE does not work

### ISSUE THREAD

**Issue by tischi** [embl-cba/microglia-morphometry#13]
> Following on the plugin use, I couldn’t make the Mobie explorer work like you do in the documentation: the table does not open (headers are for some reason not recognized). Could you confirm that it works for you? The interface seems to be slightly different now than the one you show on the screenshot, so I’m thinking maybe something else could have changed.

https://forum.image.sc/t/microglia-morphometry-fiji-plugin-parameters-cell-size-not-working/95045/4

**Comment by tischi** [comment]
I ran the segmentation and morphometry on a small crop of your data, which resulted in this folder with files:
[test.zip](https://github.com/embl-cba/microglia-morphometry/files/15141057/test.zip)

Then in MoBIE, I could open them with

##### Java Code

```Java
OpenTableCommand command = new OpenTableCommand();
command.root = new File("/Users/tischer/Desktop/microglia-data/test");
command.table = new File("/Users/tischer/Desktop/microglia-data/test/test-crop-8bit-ds2.csv");
command.images = "Path_Intensities=Signal";
command.labels = "Path_LabelMasks=Segmentation";
command.removeSpatialCalibration = true;
command.run();
```

##### ImageJ GUI Screenshot

<img width="944" alt="image" src="https://github.com/embl-cba/microglia-morphometry/assets/2157566/d0254a67-b927-482f-ad67-62ada02f333b">

------

Can you reproduce this?

**Comment by mambroset** [comment]
No it does not work with the data you provided either:
In the Log I get 
# MoBIE
Opening data from table: C:\Users\mambroset\Desktop\test\test-crop-8bit-ds2.csv
[WARNING] Found duplicate column names, e.g.: 9.219544457292887
[WARNING] Trying now to open the table assuming that there are two header rows...

And in the Console:
[ERROR] Command errored: Open Table...
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.embl.mobie.lib.table.saw.TableOpener.dealWithTwoHeaderRowsIfNeeded(TableOpener.java:250)
	at org.embl.mobie.lib.table.saw.TableOpener.openDelimitedTextFile(TableOpener.java:220)
	at org.embl.mobie.lib.table.saw.TableOpener.openDelimitedTextFile(TableOpener.java:274)
	at org.embl.mobie.lib.SourcesFromTableCreator.<init>(SourcesFromTableCreator.java:60)
	at org.embl.mobie.MoBIE.<init>(MoBIE.java:182)
	at org.embl.mobie.command.open.OpenTableCommand.run(OpenTableCommand.java:105)
	at org.embl.mobie.command.open.OpenTableCommand.run(OpenTableCommand.java:78)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I'm wondering if it has to do with the way it recognizes the headers in a csv table but I have no clue where to look to fix it! Is it possible that it's a weird difference between OSs?

**Comment by tischi** [comment]
Yes, it is possible that the OS plays a role, in which case this is also difficult to debug for me, because I do not have access to a Windows computer.

Could you do me a favour and try whether it also does not work with the [MoBIE-beta](https://github.com/mobie/mobie-viewer-fiji/blob/main/MOBIE-BETA.md) update site? This update site contains a newer version of MoBIE....

However, it indeed feels more like an OS issue, it seems like your computer does not recognise the **line breaks** in the CSV, that's why it considers `9.219544457292887` a column header even though that is already part of the normal table rows; super weird though...sorry, also a bit speechless right now...

**Comment by mambroset** [comment]
Same behavior with MoBIE-beta!
I have no clue what could be wrong...

**Comment by tischi** [comment]
I am using the Java tablesaw library to open the tables. Seems like other people [had similar issues before](https://github.com/jtablesaw/tablesaw/issues/107).

**Comment by tischi** [comment]
I asked also for us: https://github.com/jtablesaw/tablesaw/issues/1255

**Comment by mambroset** [comment]
Thanks for the dedication!
I confirm that a simple workaround for now is to open and save the csv tables before opening them with MoBIE! Doing so in Fiji works perfectly fine so it's easily scriptable :).

**Comment by tischi** [comment]
Thanks for finding this out! This is so weird 🤯

**Comment by tischi** [comment]
@mambroset could you please share here with me the table _after_ re-saving from Fiji?

**Comment by mambroset** [comment]
[iMGL_AAV2MOI105_6h_DAPI_IBA1_well6_image2_C2.csv](https://github.com/embl-cba/microglia-morphometry/files/15148804/iMGL_AAV2MOI105_6h_DAPI_IBA1_well6_image2_C2.csv)

**Comment by tischi** [comment]
Hi,

I would like to mention that the MoBIE-beta update site is deprecated now. Please from now on only use the "normal" MoBIE update site.

**Comment by tischi** [comment]
Hi @mambroset, I just found this old issue. Is that still a problem?

**Comment by mambroset** [comment]
Hi @tischi ! Had to unearth that particular project to find out haha ;). I don't have my old install anymore but I can confirm that on a new install of Fiji + Microglia Morphometry + MoBIE on Windows 10, there no longer seems to be a problem with the tables (I did not have to go through the re-saving trick to open the table). No clue if it has to do with a Windows update or anything else, but it seems fine!

**Comment by tischi** [comment]
Hi, great. Thanks a lot for looking into this. Then I can let this issue rest in peace :-)
